// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/user.grpc

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// A compilation error at this line likely means your copy of the
// grpc package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the grpc package

type User struct {
	Username             string               `protobuf:"bytes,1,opt,name=Username,json=username,proto3" json:"Username,omitempty"`
	Password             string               `protobuf:"bytes,2,opt,name=Password,json=password,proto3" json:"Password,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,3,opt,name=Created,json=created,proto3" json:"Created,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "grpc.User")
}

func init() { proto.RegisterFile("grpc/user.grpc", fileDescriptor_d570e3e37e5899c5) }

var fileDescriptor_d570e3e37e5899c5 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8d, 0x4d, 0xaa, 0x83, 0x30,
	0x14, 0x85, 0x9f, 0xaf, 0x3f, 0xda, 0x38, 0x29, 0x19, 0x49, 0x26, 0x15, 0xa1, 0xe0, 0x28, 0x82,
	0x75, 0x07, 0x6e, 0x40, 0x6c, 0xbb, 0x80, 0xa8, 0xb7, 0x22, 0xd4, 0x46, 0x6e, 0x62, 0xbb, 0xfd,
	0x92, 0x44, 0xa1, 0xa3, 0x73, 0x3f, 0xce, 0xb9, 0x7c, 0xe4, 0x38, 0xa1, 0xd4, 0x32, 0x9b, 0x15,
	0x20, 0xb7, 0x27, 0xdd, 0xd9, 0x60, 0xa7, 0x5e, 0xca, 0xfe, 0x09, 0x99, 0xa5, 0x66, 0x7e, 0x64,
	0x7a, 0x18, 0x41, 0x69, 0x31, 0x4e, 0x6e, 0x97, 0x68, 0xb2, 0xbd, 0x2b, 0x40, 0xca, 0x48, 0x60,
	0xf2, 0x25, 0x46, 0x88, 0xbc, 0xd8, 0x4b, 0x0f, 0x75, 0x30, 0x2f, 0x6c, 0xba, 0x4a, 0x28, 0xf5,
	0x91, 0xd8, 0x45, 0xff, 0xae, 0x9b, 0x16, 0xa6, 0x05, 0xf1, 0x4b, 0x04, 0xa1, 0xa1, 0x8b, 0x36,
	0xb1, 0x97, 0x86, 0x39, 0xe3, 0x4e, 0xc9, 0x57, 0x25, 0xbf, 0xad, 0xca, 0xda, 0x6f, 0xdd, 0x34,
	0x2f, 0x48, 0x68, 0x6c, 0x57, 0xc0, 0xf7, 0xd0, 0x02, 0x3d, 0x13, 0xdf, 0x60, 0x5d, 0x95, 0x34,
	0x74, 0x7f, 0xdc, 0x30, 0xfb, 0x85, 0xe4, 0xaf, 0xd9, 0x5b, 0xba, 0x7c, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x09, 0x0f, 0x7e, 0x38, 0xee, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	UserRPC(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) UserRPC(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/grpc.UserService/UserRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	UserRPC(context.Context, *User) (*User, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) UserRPC(ctx context.Context, req *User) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserRPC not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_UserRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.UserService/UserRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserRPC(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserRPC",
			Handler:    _UserService_UserRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/user.grpc",
}
